### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by whisperzh** [Luomingbear/SlideButton#1]
想请教一下那个setChecked函数您是不是没写

**Comment by Luomingbear** [comment]
你是想要调用之后有一个移动动画吗？调用setCheckedWithAnimation可以有动画效果的

**Comment by whisperzh** [comment]
是的，但是调用之后没有反应，不管值是true还是false都没有反应（悲）

**Comment by Luomingbear** [comment]
我刚才试了一下是有动画效果的，想问下你按钮的大小是用具体的dp还是wrap_content呢？用wrap_content的话因为没有具体大小所以不会有效果的

**Comment by whisperzh** [comment]
好吧，那我再试试
